const albums={
"2026-10-03":{title:"Kiss All the Time. Disco, Occasionally.",artist:"Harry Styles",genre:"Synth Pop",rating:"8.6",track:"Carla's Song",release:"March 6, 2026",tracks:"12",length:"43 min",recommended:"Mia W",singles:["Aperture","American Girls","Dance No More"],cover:"https://coverartarchive.org/release/35c23d9f-9765-42c2-9ef4-f28fa61c11a3/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/69BqE1V8Bzb9GCyeP1fFeR"},
"2026-10-02":{title:"GABRIEL",artist:"keshi",genre:"Art Pop",rating:"8.7",track:"UNDERSTAND",release:"March 25, 2022",tracks:"12",length:"33 min",recommended:"N/A",singles:["GET IT","SOMEBODY","UNDERSTAND"],cover:"https://coverartarchive.org/release/43665699-1d57-4963-82dd-27189b4509d7/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/1WVIJaAboRSwJOe4u0n0Q7"},
"2026-10-01":{title:"Swimming",artist:"Mac Miller",genre:"Pop Rap",rating:"8.6",track:"Small Worlds",release:"August 3, 2018",tracks:"13",length:"58 min",recommended:"N/A",singles:["Self Care","Small Worlds","What's the Use?"],cover:"https://coverartarchive.org/release/6db76635-a3cd-4933-85e9-e29cbbc38c1c/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/5wtE5aLX5r7jOosmPhJhhk"},
"2026-09-30":{title:"Blue Hawaii",artist:"Elvis Presley",genre:"Pop",rating:"8.5",track:"Can't Help Falling in Love",release:"October 20, 1961",tracks:"14",length:"32 min",recommended:"N/A",singles:["Can't Help Falling in Love","Rock-A-Hula Baby"],cover:"https://coverartarchive.org/release/c2a983c4-d1c9-49d0-8fe8-9c60f8879c2b/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/7xe8VI48TxUpU1IIo0RfGi"},
"2026-09-29":{title:"Parachutes",artist:"Coldplay",genre:"Alternative Rock",rating:"8.3",track:"Yellow",release:"July 10, 2000",tracks:"10",length:"42 min",recommended:"N/A",singles:["Shiver","Yellow","Trouble"],cover:"https://miro.medium.com/v2/resize%3Afit%3A1400/1%2A0oVE6OlfBYI0B83h56kZyA.png",spotify:"https://open.spotify.com/embed/album/4sObgJ1G4jahxdcWTEdeWK"},
"2026-09-28":{title:"Strangers In The Night",artist:"Frank Sinatra",genre:"Traditional Pop",rating:"8.5",track:"Strangers In The Night",release:"May 30, 1966",tracks:"10",length:"27 min",recommended:"N/A",singles:["Strangers in the Night","Summer Wind"],cover:"https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/9c/32/e3/9c32e334-d02f-6532-a563-f54a68d20e24/00602547197238.rgb.jpg/1200x630bb.jpg",spotify:"https://open.spotify.com/embed/album/4Qf6H33qdAhMFW17xfjBJB"},
"2026-09-27":{title:"Remember That You Will Die",artist:"Polyphia",genre:"Math Rock",rating:"6",track:"ABC",release:"October 28, 2022",tracks:"12",length:"39 min",recommended:"Dietrich B",singles:["ABC","Playing God","Neurotica","Ego Death"],cover:"https://coverartarchive.org/release/1c50f5e6-5d2a-4d18-9d37-a45e08ddfbcd/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/3cN3mENkACWuRCDOuQUtfw"},
"2026-09-26":{title:"Can We Hang Out Sometime?",artist:"Good Kid",genre:"Indie Rock",rating:"5.8",track:"Tea Leaves",release:"April 3, 2026",tracks:"10",length:"26 min",recommended:"Altay",singles:[],cover:"https://f4.bcbits.com/img/a4078181728_16.jpg",spotify:"https://open.spotify.com/embed/album/2ude1QTWRjfCQYgpr5mc11"},
"2026-09-25":{title:"With Heaven On Top",artist:"Zach Bryan",genre:"Country",rating:"8.6",track:"Plastic Cigarette",release:"January 9, 2026",tracks:"25",length:"1 hr 18 min",recommended:"Ali M",singles:["Plastic Cigarette","Say Why"],cover:"https://coverartarchive.org/release/5d1ba863-a4ca-4286-889c-d92afe1b41ec/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/4NvMwUFmY1dcDEgD8KoQjG"},
"2026-09-24":{title:"Flex Musix",artist:"OsamaSon",genre:"Trap",rating:"5",track:"Kills",release:"December 8, 2023",tracks:"17",length:"37 min",recommended:"Reem",singles:[],cover:"https://coverartarchive.org/release/15e12e73-ef34-40a6-8989-cb60c34be3cf/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/075lV4wdtLwFvIvCUdSYhL"},
"2026-09-23":{title:"Wildflowers",artist:"Tom Petty",genre:"Folk Rock",rating:"8",track:"You Wreck Me",release:"November 1, 1994",tracks:"15",length:"1 hr 2 min",recommended:"Mom",singles:["You Don't Know How It Feels","You Wreck Me","It's Good to Be King","A Higher Place"],cover:"https://coverartarchive.org/release/6a87e042-f9d6-437d-a218-263aceaa209b/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/3ZGUBwDiY5HPOcWv4SBPQg"},
"2026-09-22":{title:"Visitor",artist:"Sienna Spiro",genre:"Pop",rating:"8",track:"The Visitor",release:"July 3, 2026",tracks:"10",length:"33 min",recommended:"Bridgette L",singles:["Die On This Hill","You Stole The Show","The Visitor"],cover:"https://imageseu.urbndata.com/is/image/UrbanOutfittersEU/0550434960797_000_a2?%24xlarge%24=&fit=constrain&qlt=80&wid=640",spotify:"https://open.spotify.com/embed/album/1vcbnpnQfghE8vRxhvUF60"},
"2026-09-21":{title:"The Great Divide",artist:"Noah Kahan",genre:"Folk Rock",rating:"8.7",track:"Orbiter",release:"April 24, 2026",tracks:"21",length:"1 hr 36 min",recommended:"Marin G.",singles:["The Great Divide","Porch Light"],cover:"https://spindizzyrecords.com/cdn/shop/files/Noah_Kahan_-_The_Great_Divide_-_CD_-_2026.jpg?v=1769627303",spotify:"https://open.spotify.com/embed/album/01HMeEWI4jOmTIDHGaGI1n"},
"2026-09-20":{title:"Love Deluxe",artist:"Sade",genre:"Contemporary R&B",rating:"7.8",track:"Kiss of Life",release:"October 25, 1992",tracks:"9",length:"46 min",recommended:"Ryan Gigs",singles:["No Ordinary Love","Feel No Pain","Kiss of Life","Cherish the Day"],cover:"https://coverartarchive.org/release/49c1eeeb-919f-33d2-b72d-71b3fa5572cf/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/6Y8lHGQqTmbE6Hhj1mMCkX"},
"2026-09-13":{title:"Harry Styles",artist:"Harry Styles",genre:"Pop",rating:"7.9",track:"Sign of the Times",release:"May 12, 2017",tracks:"10",length:"40 min",recommended:"—",singles:["Sign of the Times","Two Ghosts","Kiwi","Sweet Creature"],cover:"https://www.officialcharts.com/sites/default/files/styles/content_column_mobile/public/legacy_images/media/652652/harry-styles-album-artwork.jpg?itok=VTBt75Md",spotify:"https://open.spotify.com/embed/album/1FZKIm3JVDCxTchXDo5jOV"},
"2026-09-14":{title:"NEVER ENOUGH",artist:"Daniel Caesar",genre:"Contemporary R&B",rating:"8.5",track:"Always",release:"April 7, 2023",tracks:"15",length:"54 min",recommended:"—",singles:["Do You Like Me?","Let Me Go"],cover:"https://i.ebayimg.com/images/g/DdMAAeSwzzdotIHl/s-l1200.jpg",spotify:"https://open.spotify.com/embed/album/2z9lM6LDS58F70IGyQ1XMK"},
"2026-09-15":{title:"Blonde",artist:"Frank Ocean",genre:"Alternative R&B",rating:"8",track:"Godspeed",release:"August 20, 2016",tracks:"17",length:"51 min",recommended:"Ryan Gigs",singles:["Nikes"],cover:"https://i.pinimg.com/originals/fc/5b/ff/fc5bffebeb977cbd99d49afb97e7fd0f.jpg",spotify:"https://open.spotify.com/embed/album/3mH6qwIy9crq0I9YQbOuDf"},
"2026-09-16":{title:"Oh yeah?",artist:"Steve Lacy",genre:"Alternative",rating:"7.6",track:"Doom",release:"2025",tracks:"—",length:"—",recommended:"—",singles:["Nice Shoes"],cover:"https://lunchboxrecords.com/cdn/shop/files/SteveLacyOhyeah_LP_580x%402x.jpg?v=1781006823",spotify:"https://open.spotify.com/embed/prerelease/3oNqPJdm4RVcst8SQnS6by"},
"2026-09-17":{title:"Requiem",artist:"keshi",genre:"Pop",rating:"8.5",track:"Soft Spot",release:"February 7, 2025",tracks:"13",length:"43 min",recommended:"Mia W.",singles:["Soft Spot","Dream","Say","Texas"],cover:"https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/a6/a3/20/a6a32054-f43f-12b3-4019-1f201b6c56b2/24UMGIM70300.rgb.jpg/1200x630bb.jpg",spotify:"https://open.spotify.com/embed/album/5DfKDonIvNlxlzA4ORIOFm"},
"2026-09-18":{title:"August and Everything After",artist:"Counting Crows",genre:"Alt Rock",rating:"8.4",track:"Round Here",release:"September 14, 1993",tracks:"11",length:"51 min",recommended:"Dad",singles:["Mr. Jones","Round Here","Omaha","Rain King","A Murder of One"],cover:"https://cdn.prod.website-files.com/5fda4244c42e015b06d2fd8d/5fda462b0dcfee387c3ccf87_august-and-everything-after_album.avif",spotify:"https://open.spotify.com/embed/album/1dBjJZRfh3ZwZEyVwaTbV0"},
"2026-09-19":{title:"The Bends",artist:"Radiohead",genre:"Alt Rock",rating:"8.4",track:"Fake Plastic Trees",release:"March 13, 1995",tracks:"12",length:"48 min",recommended:"—",singles:["My Iron Lung","High and Dry","Fake Plastic Trees","Just","Street Spirit (Fade Out)"],cover:"https://coverartarchive.org/release/b2002626-ea4f-47d4-972d-1aa229335321/front-1200.jpg",spotify:"https://open.spotify.com/embed/album/35UJLpClj5EDrhpNIi4DFg"},
};
const pad=n=>String(n).padStart(2,"0");
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const todayKey=()=>key(new Date());
let selected=todayKey();
let view=new Date(new Date().getFullYear(),new Date().getMonth(),1);
let imageCache={};

function getCover(a){return a?.cover||null}
function openCalendar(){document.getElementById("calendarModal").hidden=false;document.getElementById("calendarModal").classList.add("open");document.getElementById("calendarModal").setAttribute("aria-hidden","false");renderCalendar()}
function closeCalendar(){document.getElementById("calendarModal").classList.remove("open");document.getElementById("calendarModal").hidden=true;document.getElementById("calendarModal").setAttribute("aria-hidden","true")}
function renderCalendar(){
 document.getElementById("monthLabel").textContent=view.toLocaleString("en-US",{month:"long",year:"numeric"});
 const cal=document.getElementById("calendar");cal.innerHTML="";
 const first=new Date(view.getFullYear(),view.getMonth(),1),start=new Date(first);start.setDate(1-first.getDay());
 for(let i=0;i<42;i++){
  const d=new Date(start);d.setDate(start.getDate()+i);const k=key(d),a=albums[k],el=document.createElement("button");
  el.className="day"+(d.getMonth()!==view.getMonth()?" other":"")+(a?" has-album":"")+(k===selected?" selected":"");
  el.innerHTML=`<div class="date-num">${d.getDate()}</div>${a?`<div class="album-mini"><strong>${a.title}</strong><span>${a.artist}</span></div>`:""}`;
  el.addEventListener("click",()=>{selected=k;renderToday();closeCalendar()});
  cal.appendChild(el);
 }
}
async function renderToday(){
 const box=document.getElementById("detail"),a=albums[selected],d=new Date(selected+"T12:00:00"),isToday=selected===todayKey();
 if(!a){box.innerHTML=`<div class="empty"><div class="big">♫</div><div class="date">${d.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}${isToday?'<span class="today-label">TODAY</span>':""}</div><h2>No album yet</h2><p>This day is ready for its one-a-day album.</p></div>`;return}
 box.innerHTML=`<div class="cover-wrap"><div class="cover-fallback">${a.artist.slice(0,2).toUpperCase()}</div></div><div class="info"><div class="date">${d.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}${isToday?'<span class="today-label">TODAY</span>':""}</div><h2>${a.title}</h2><div class="artist">${a.artist}</div><div class="rating">★ <b>${a.rating}</b> / 10</div><div class="meta"><div><label>Genre</label><div>${a.genre}</div></div><div><label>Best track</label><div>${a.track}</div></div><div class="meta-row-two"><div><label>Released</label><div>${a.release}</div></div><div><label>Tracks</label><div>${a.tracks}</div></div><div><label>Length</label><div>${a.length}</div></div></div></div>${a.recommended&&a.recommended!=="—"?`<div class="recommend">Recommended by: <strong>${a.recommended}</strong></div>`:""}</div><aside class="singles"><div class="section-kicker">SINGLES</div><div class="single-list">${(a.singles||[]).map((x,n)=>`<div class="single"><span class="single-number">${String(n+1).padStart(2,"0")}</span><strong>${x}</strong></div>`).join("")}</div>${a.spotify?`<div class="listen-block"><div class="section-kicker">LISTEN</div><iframe class="spotify-embed" src="${a.spotify}" title="Listen to ${a.title} by ${a.artist} on Spotify" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe><a class="spotify-link" href="${a.spotify.replace("/embed/","/")}" target="_blank" rel="noopener">Open in Spotify ↗</a></div>`:""}</aside>`;
 const url=getCover(a);if(url){const wrap=document.querySelector(".cover-wrap");if(wrap){const img=document.createElement("img");img.className="cover";img.alt=`${a.title} by ${a.artist} album cover`;img.src=url;img.onerror=()=>{img.remove();wrap.innerHTML=`<div class="cover-fallback">${a.artist.slice(0,2).toUpperCase()}</div>`;};wrap.replaceChildren(img)}}
}
function changeDay(offset){const d=new Date(selected+"T12:00:00");d.setDate(d.getDate()+offset);selected=key(d);renderToday();}
document.getElementById("prevDay").onclick=()=>changeDay(-1);document.getElementById("nextDay").onclick=()=>changeDay(1);document.getElementById("calendarButton").onclick=openCalendar;
document.getElementById("closeCalendar").onclick=closeCalendar;
document.getElementById("modalBackdrop").onclick=closeCalendar;
document.getElementById("prevMonth").onclick=()=>{view.setMonth(view.getMonth()-1);renderCalendar()};
document.getElementById("nextMonth").onclick=()=>{view.setMonth(view.getMonth()+1);renderCalendar()};
document.getElementById("todayButton").onclick=()=>{selected=todayKey();view=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderToday();closeCalendar()};
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCalendar()});
renderToday();
